theme: jekyll-theme-architect
title: "Project LibreRespire"
description: "LibreRespire is a project for  developing an open source design for a medical ventilator machine (also known as a 'breathing machine')."
